version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app